// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SocialConstants
{
        public const string achievement_messy_mayhem = "CgkIgpqt_u0CEAIQBg"; // <GPGSID>
        public const string achievement_soothing_song = "CgkIgpqt_u0CEAIQBw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIgpqt_u0CEAIQAQ"; // <GPGSID>
        public const string leaderboard_high_combo = "CgkIgpqt_u0CEAIQAg"; // <GPGSID>
        public const string achievement_focused_flipper = "CgkIgpqt_u0CEAIQBA"; // <GPGSID>
        public const string achievement_good_grip = "CgkIgpqt_u0CEAIQBQ"; // <GPGSID>
        public const string achievement_table_tirade = "CgkIgpqt_u0CEAIQCA"; // <GPGSID>
        public const string leaderboard_most_flips = "CgkIgpqt_u0CEAIQAw"; // <GPGSID>

}

